import type { BasicEnglishUnitSeed } from "./basic-english-content";
import { buildBasicEnglishLessons } from "./basic-english-content";

export const advancedEnglishUnits: BasicEnglishUnitSeed[] = [
  {
    slug: "science-and-technology", title: "Bài 1 · Khoa học và công nghệ", theme: "Science and technology", description: "Giải thích công nghệ hoạt động ra sao, cân nhắc lợi ích và rủi ro trong đời sống.", grammar: "Mệnh đề quan hệ; bị động với động từ khuyết thiếu.",
    words: [["innovation", "đổi mới"], ["device", "thiết bị"], ["research", "nghiên cứu"], ["evidence", "bằng chứng"], ["efficient", "hiệu quả"], ["automate", "tự động hóa"], ["privacy", "quyền riêng tư"], ["accurate", "chính xác"], ["breakthrough", "bước đột phá"], ["ethical", "có đạo đức"]],
    sentences: [["How could this technology improve daily life?", "Công nghệ này có thể cải thiện đời sống hằng ngày thế nào?", "Em hỏi về tác động thực tế của một phát minh."], ["It could automate repetitive tasks and save time.", "Nó có thể tự động hóa việc lặp lại và tiết kiệm thời gian.", "Em giải thích một lợi ích cụ thể."], ["What risks should we consider before using it?", "Ta nên cân nhắc rủi ro nào trước khi dùng nó?", "Em chuyển cuộc trao đổi sang mặt hạn chế."], ["Personal data must be protected carefully.", "Dữ liệu cá nhân phải được bảo vệ cẩn thận.", "Em nêu một nguyên tắc sử dụng có trách nhiệm."]],
    practice: [{ prompt: "Hoàn thành: This is a device ___ measures air quality.", options: ["who", "which", "where"], correctIndex: 1, explanation: "Which thay cho vật trong mệnh đề quan hệ." }, { prompt: "Hoàn thành: User data must ___ securely.", options: ["store", "be stored", "stored"], correctIndex: 1, explanation: "Sau must ở thể bị động dùng be + quá khứ phân từ." }],
    visuals: ["💡", "📱", "🔬", "🧾", "⚡", "🤖", "🔐", "🎯", "🚀", "⚖️", "🤔💡", "🤖⏱️", "⚠️❓", "🔐✅"],
  },
  {
    slug: "household-problems", title: "Bài 2 · Sự cố trong nhà", theme: "Household problems", description: "Mô tả sự cố, xác định nguyên nhân và trao đổi giải pháp với thợ sửa chữa.", grammar: "Câu sai khiến have/get something done; suy đoán với might/must.",
    words: [["leak", "rò rỉ"], ["blocked", "bị tắc"], ["faulty", "bị lỗi"], ["repair", "sửa chữa"], ["maintenance", "bảo trì"], ["electrician", "thợ điện"], ["plumber", "thợ sửa ống nước"], ["estimate", "báo giá ước tính"], ["warranty", "bảo hành"], ["urgent", "khẩn cấp"]],
    sentences: [["The kitchen sink has been leaking since last night.", "Bồn rửa bếp bị rò từ tối qua.", "Em mô tả rõ sự cố và thời điểm bắt đầu."], ["The pipe might be blocked under the sink.", "Đường ống có thể bị tắc dưới bồn rửa.", "Em đưa ra phỏng đoán chưa chắc chắn."], ["Could you give me an estimate before repairing it?", "Anh/chị có thể báo giá trước khi sửa không?", "Em hỏi chi phí một cách lịch sự."], ["I'll have the pipe replaced this afternoon.", "Tôi sẽ cho thay đường ống chiều nay.", "Em dùng cấu trúc sai khiến khi thuê người sửa."]],
    practice: [{ prompt: "Hoàn thành: We need to have the heater ___.", options: ["repair", "repaired", "repairing"], correctIndex: 1, explanation: "Have something done dùng quá khứ phân từ." }, { prompt: "The lights are off; there ___ be a power cut.", options: ["might", "has", "does"], correctIndex: 0, explanation: "Might diễn tả một khả năng chưa chắc chắn." }],
    visuals: ["💧", "🚫", "⚠️", "🔧", "🛠️", "⚡", "🚰", "💵", "📄", "🚨", "🚰💧", "🔍🚿", "💵❓", "🔧✅"],
  },
  {
    slug: "travel-and-transportation", title: "Bài 3 · Du lịch và giao thông", theme: "Travel and transportation", description: "Xử lý thay đổi hành trình, hỏi phương án thay thế và khiếu nại lịch sự.", grammar: "Câu điều kiện hỗn hợp đơn giản; câu hỏi gián tiếp.",
    words: [["itinerary", "lịch trình"], ["connection", "chuyến nối"], ["delay", "trì hoãn"], ["departure", "khởi hành"], ["destination", "điểm đến"], ["alternative", "phương án thay thế"], ["compensation", "bồi thường"], ["reservation", "đặt chỗ"], ["transfer", "chuyển tuyến"], ["customs", "hải quan"]],
    sentences: [["Could you tell me why the train has been delayed?", "Anh/chị có thể cho tôi biết vì sao tàu bị trễ không?", "Em hỏi thông tin tại quầy dịch vụ."], ["A technical issue has affected the departure time.", "Một sự cố kỹ thuật đã ảnh hưởng giờ khởi hành.", "Nhân viên giải thích nguyên nhân."], ["If I miss my connection, what are my options?", "Nếu lỡ chuyến nối, tôi có những lựa chọn nào?", "Em chủ động hỏi phương án dự phòng."], ["We can transfer your booking to the next service.", "Chúng tôi có thể chuyển đặt chỗ sang chuyến tiếp theo.", "Nhân viên đề xuất giải pháp."]],
    practice: [{ prompt: "Chọn câu hỏi gián tiếp đúng.", options: ["Could you tell me why is it late?", "Could you tell me why it is late?", "Could you tell why it late?"], correctIndex: 1, explanation: "Câu hỏi gián tiếp dùng trật tự chủ ngữ + động từ." }, { prompt: "If I miss the train, I ___ the next one.", options: ["take", "will take", "took"], correctIndex: 1, explanation: "Điều kiện loại 1 dùng will ở mệnh đề kết quả." }],
    visuals: ["🗺️", "🔗", "⏳", "🚆", "📍", "🔄", "💳", "🎫", "🚉", "🛂", "🚆❓", "⚙️⏳", "🔗❓", "🎫🔄"],
  },
  {
    slug: "fashion-and-style", title: "Bài 4 · Thời trang và phong cách", theme: "Fashion and style", description: "Mô tả phong cách, chất liệu và lựa chọn tiêu dùng có trách nhiệm.", grammar: "Cụm phân từ mô tả; so sánh nâng cao với far/slightly.",
    words: [["fabric", "chất liệu vải"], ["pattern", "họa tiết"], ["tailored", "được may đo"], ["casual", "thường ngày"], ["formal", "trang trọng"], ["durable", "bền"], ["sustainable", "bền vững"], ["trend", "xu hướng"], ["accessory", "phụ kiện"], ["versatile", "linh hoạt, đa dụng"]],
    sentences: [["What kind of outfit would suit this event?", "Trang phục nào phù hợp sự kiện này?", "Em hỏi lời khuyên trước một dịp quan trọng."], ["Something formal but comfortable would work well.", "Đồ trang trọng nhưng thoải mái sẽ phù hợp.", "Em cân bằng hai yêu cầu khi tư vấn."], ["This jacket is far more versatile than the other one.", "Áo khoác này đa dụng hơn hẳn chiếc kia.", "Em so sánh hai lựa chọn."], ["I prefer clothing made from durable materials.", "Tôi thích quần áo làm từ chất liệu bền.", "Em nêu tiêu chí mua sắm có trách nhiệm."]],
    practice: [{ prompt: "Hoàn thành: This design is ___ more practical.", options: ["far", "very", "many"], correctIndex: 0, explanation: "Far có thể nhấn mạnh so sánh hơn." }, { prompt: "Chọn cụm đúng.", options: ["clothes making from cotton", "clothes made from cotton", "clothes make from cotton"], correctIndex: 1, explanation: "Made from là cụm phân từ bị động bổ nghĩa cho clothes." }],
    visuals: ["🧵", "🔷", "🪡", "👕", "🤵", "🛡️", "🌿", "📈", "👜", "🔁", "👗❓", "🤵🙂", "🧥⚖️", "🌿👕"],
  },
  {
    slug: "advanced-review-one", title: "Ôn tập 1 · Bài 1–4", theme: "Công nghệ, nhà cửa, hành trình và phong cách", description: "Củng cố giải thích, suy đoán, câu hỏi gián tiếp và so sánh nâng cao.", grammar: "Tổng hợp cấu trúc của bài 1 đến bài 4.",
    words: [["evaluate", "đánh giá"], ["solution", "giải pháp"], ["consequence", "hệ quả"], ["reliable", "đáng tin"], ["practical", "thiết thực"], ["request", "yêu cầu"], ["clarify", "làm rõ"], ["compare", "so sánh"], ["priority", "ưu tiên"], ["responsible", "có trách nhiệm"]],
    sentences: [["Could you clarify how this device is maintained?", "Anh/chị có thể làm rõ thiết bị này được bảo trì thế nào không?", "Em kết hợp công nghệ với câu hỏi gián tiếp."], ["It must be checked by a qualified technician.", "Nó phải được kiểm tra bởi kỹ thuật viên đủ chuyên môn.", "Em dùng bị động với must."], ["If the service is delayed, we will need an alternative.", "Nếu dịch vụ bị trễ, chúng ta sẽ cần phương án khác.", "Em phản ứng trước thay đổi kế hoạch."], ["The more durable option is usually more practical.", "Lựa chọn bền hơn thường thiết thực hơn.", "Em đưa ra đánh giá có lý do."]],
    practice: [{ prompt: "The system must ___ regularly.", options: ["check", "be checked", "checked"], correctIndex: 1, explanation: "Bị động sau must: be + quá khứ phân từ." }, { prompt: "Could you explain where ___?", options: ["is the station", "the station is", "the station"], correctIndex: 1, explanation: "Câu hỏi gián tiếp giữ trật tự câu kể." }],
    visuals: ["📊", "🧩", "🔮", "✅", "🛠️", "📩", "🔎", "⚖️", "🎯", "🤝", "🔧❓", "👷✅", "⏳🔄", "🛡️👍"],
  },
  {
    slug: "tastes-and-senses", title: "Bài 5 · Vị giác và giác quan", theme: "Tastes and senses", description: "Mô tả cảm nhận tinh tế, so sánh món ăn và phản hồi lịch sự.", grammar: "Động từ giác quan + tính từ; cấu trúc seem/appear to.",
    words: [["aroma", "hương thơm"], ["texture", "kết cấu"], ["bitter", "đắng"], ["savoury", "mặn, đậm vị"], ["subtle", "tinh tế, nhẹ"], ["overpowering", "quá nồng"], ["crisp", "giòn"], ["tender", "mềm"], ["aftertaste", "hậu vị"], ["fragrant", "thơm"]],
    sentences: [["What do you think of the flavour?", "Bạn thấy hương vị thế nào?", "Em xin nhận xét về một món ăn."], ["It tastes slightly bitter at first.", "Ban đầu nó có vị hơi đắng.", "Em mô tả mức độ chính xác hơn."], ["The aroma seems stronger than the flavour.", "Mùi thơm có vẻ đậm hơn vị.", "Em so sánh hai cảm nhận."], ["The texture is crisp outside but tender inside.", "Kết cấu giòn bên ngoài nhưng mềm bên trong.", "Em mô tả món ăn bằng sự tương phản."]],
    practice: [{ prompt: "Hoàn thành: The soup tastes ___.", options: ["well", "delicious", "deliciously"], correctIndex: 1, explanation: "Sau taste dùng tính từ." }, { prompt: "The aroma seems ___ stronger.", options: ["be", "to be", "being"], correctIndex: 1, explanation: "Seem + to be + tính từ." }],
    visuals: ["👃", "🧶", "🍫", "🍲", "🌱", "🌶️", "🍎", "🥩", "☕", "🌸", "🍽️❓", "🍫🙂", "👃⚖️", "🥖🥩"],
  },
  {
    slug: "relationships-and-commitment", title: "Bài 6 · Quan hệ và cam kết", theme: "Relationships and commitment", description: "Trao đổi kỳ vọng, giải quyết bất đồng và thể hiện sự tôn trọng trong quan hệ.", grammar: "Câu điều kiện loại 2; động từ tường thuật và lời khuyên gián tiếp.",
    words: [["commitment", "cam kết"], ["compromise", "thỏa hiệp"], ["expectation", "kỳ vọng"], ["misunderstanding", "hiểu lầm"], ["supportive", "biết hỗ trợ"], ["trust", "tin tưởng"], ["boundary", "ranh giới"], ["appreciate", "trân trọng"], ["resolve", "giải quyết"], ["honest", "chân thành"]],
    sentences: [["I think we may have misunderstood each other.", "Tôi nghĩ có thể chúng ta đã hiểu lầm nhau.", "Em mở đầu một cuộc trao đổi khó một cách bình tĩnh."], ["Could we talk about what each of us expected?", "Chúng ta có thể nói về điều mỗi người kỳ vọng không?", "Em làm rõ nhu cầu thay vì đổ lỗi."], ["If I were in your position, I'd ask for some time.", "Nếu ở vị trí của bạn, tôi sẽ xin thêm thời gian.", "Em đưa lời khuyên nhẹ nhàng."], ["I appreciate your being honest with me.", "Tôi trân trọng việc bạn chân thành với tôi.", "Em ghi nhận sự cởi mở của đối phương."]],
    practice: [{ prompt: "If I ___ you, I would listen first.", options: ["am", "were", "will be"], correctIndex: 1, explanation: "Điều kiện loại 2 thường dùng If I were you." }, { prompt: "She said that she ___ more time.", options: ["needed", "needs", "need"], correctIndex: 0, explanation: "Câu tường thuật lùi thì về needed." }],
    visuals: ["🤝", "⚖️", "🎯", "💭", "🫶", "🔐", "🚧", "💛", "🧩", "💬", "💭🤝", "💬❓", "👟💡", "💛✅"],
  },
  {
    slug: "arts-and-entertainment", title: "Bài 7 · Nghệ thuật và giải trí", theme: "Arts and entertainment", description: "Nhận xét tác phẩm, trình bày cách hiểu và bảo vệ quan điểm bằng dẫn chứng.", grammar: "Mệnh đề nhượng bộ; câu chẻ để nhấn mạnh.",
    words: [["performance", "màn trình diễn"], ["exhibition", "triển lãm"], ["interpretation", "cách diễn giải"], ["compelling", "thuyết phục, cuốn hút"], ["original", "độc đáo"], ["audience", "khán giả"], ["critique", "bài phê bình"], ["theme", "chủ đề"], ["portray", "khắc họa"], ["subtle", "tinh tế"]],
    sentences: [["What did you find most compelling about the film?", "Bạn thấy điều gì cuốn hút nhất trong phim?", "Em hỏi ý kiến sâu hơn sau khi xem."], ["It was the ending that changed my interpretation.", "Chính đoạn kết đã thay đổi cách hiểu của tôi.", "Em dùng câu chẻ để nhấn mạnh."], ["Although the plot was slow, the performances were excellent.", "Dù cốt truyện chậm, diễn xuất rất xuất sắc.", "Em đưa nhận xét cân bằng."], ["The director portrays loneliness through subtle details.", "Đạo diễn khắc họa sự cô đơn qua những chi tiết tinh tế.", "Em bảo vệ nhận xét bằng cách chỉ ra thủ pháp."]],
    practice: [{ prompt: "Hoàn thành: ___ the story was simple, it was moving.", options: ["Although", "Because", "Unless"], correctIndex: 0, explanation: "Although nối hai ý tương phản." }, { prompt: "It was the music ___ impressed me most.", options: ["who", "that", "where"], correctIndex: 1, explanation: "Câu chẻ dùng It was ... that ..." }],
    visuals: ["🎭", "🖼️", "💭", "🧲", "✨", "👥", "📝", "🎯", "🎬", "🔎", "🎞️❓", "🔚💡", "🐢👏", "🎬🔎"],
  },
  {
    slug: "workplace-safety", title: "Bài 8 · An toàn nơi làm việc", theme: "Workplace safety", description: "Nhận diện nguy cơ, báo sự cố và đề xuất biện pháp phòng ngừa rõ ràng.", grammar: "Đảo ngữ điều kiện với should; cấu trúc need + V-ing/to be done.",
    words: [["hazard", "mối nguy"], ["precaution", "biện pháp phòng ngừa"], ["protective", "có tính bảo hộ"], ["procedure", "quy trình"], ["incident", "sự cố"], ["evacuate", "sơ tán"], ["inspect", "kiểm tra"], ["comply", "tuân thủ"], ["equipment", "thiết bị"], ["supervisor", "người giám sát"]],
    sentences: [["I've noticed a potential hazard near the entrance.", "Tôi nhận thấy một mối nguy gần lối vào.", "Em báo nguy cơ trước khi xảy ra tai nạn."], ["The loose cable needs securing immediately.", "Dây cáp lỏng cần được cố định ngay.", "Em nêu hành động khắc phục cần thiết."], ["Should an incident occur, follow the evacuation procedure.", "Nếu xảy ra sự cố, hãy làm theo quy trình sơ tán.", "Em đưa hướng dẫn trang trọng."], ["I'll inform the supervisor and mark the area.", "Tôi sẽ báo người giám sát và đánh dấu khu vực.", "Em xác nhận hai hành động tiếp theo."]],
    practice: [{ prompt: "The machine needs ___.", options: ["inspect", "inspecting", "to inspecting"], correctIndex: 1, explanation: "Need + V-ing có nghĩa cần được làm." }, { prompt: "___ an emergency occur, use this exit.", options: ["Should", "Would", "Did"], correctIndex: 0, explanation: "Should + chủ ngữ + động từ là đảo ngữ điều kiện trang trọng." }],
    visuals: ["⚠️", "🛡️", "🥽", "📋", "🚨", "🏃", "🔍", "✅", "🧰", "👷", "⚠️👀", "🔌🔧", "🚨📋", "👷📣"],
  },
  {
    slug: "advanced-review-two", title: "Ôn tập 2 · Bài 5–8", theme: "Giác quan, quan hệ, nghệ thuật và an toàn", description: "Củng cố miêu tả tinh tế, lời khuyên, lập luận cân bằng và hướng dẫn an toàn.", grammar: "Tổng hợp cấu trúc của bài 5 đến bài 8.",
    words: [["perception", "cảm nhận"], ["perspective", "góc nhìn"], ["constructive", "mang tính xây dựng"], ["contrast", "tương phản"], ["emphasize", "nhấn mạnh"], ["respond", "phản hồi"], ["prevent", "ngăn ngừa"], ["acknowledge", "ghi nhận"], ["interpret", "diễn giải"], ["recommend", "khuyến nghị"]],
    sentences: [["Although our perspectives differ, I understand your concern.", "Dù góc nhìn khác nhau, tôi hiểu mối lo của bạn.", "Em thừa nhận khác biệt trước khi phản hồi."], ["What I appreciate most is the constructive feedback.", "Điều tôi trân trọng nhất là phản hồi mang tính xây dựng.", "Em nhấn mạnh điều tích cực."], ["If I were responsible for the event, I'd inspect the venue first.", "Nếu phụ trách sự kiện, tôi sẽ kiểm tra địa điểm trước.", "Em kết hợp lời khuyên và an toàn."], ["Any potential hazard should be reported immediately.", "Mọi mối nguy tiềm ẩn nên được báo ngay.", "Em đưa khuyến nghị rõ ràng."]],
    practice: [{ prompt: "___ we disagreed, the discussion was useful.", options: ["Although", "Despite of", "Because of"], correctIndex: 0, explanation: "Although đi với một mệnh đề đầy đủ." }, { prompt: "If I ___ in charge, I'd change the procedure.", options: ["were", "am", "will be"], correctIndex: 0, explanation: "Điều kiện loại 2 dùng were." }],
    visuals: ["👁️", "🔭", "🧱", "◐", "📣", "💬", "🛡️", "✅", "🧠", "👍", "⚖️💬", "💛📝", "👷🔍", "⚠️📣"],
  },
  {
    slug: "cultural-diversity", title: "Bài 9 · Đa dạng văn hóa", theme: "Cultural diversity", description: "Hỏi về khác biệt văn hóa với sự tò mò, tránh khái quát hóa và xử lý hiểu lầm.", grammar: "Cấu trúc hedging: tend to, may, in many cases; mệnh đề danh từ.",
    words: [["custom", "phong tục"], ["diversity", "sự đa dạng"], ["assumption", "giả định"], ["stereotype", "khuôn mẫu"], ["inclusive", "hòa nhập"], ["gesture", "cử chỉ"], ["etiquette", "phép lịch sự"], ["perspective", "góc nhìn"], ["adapt", "thích nghi"], ["respectful", "tôn trọng"]],
    sentences: [["Is this gesture considered polite here?", "Cử chỉ này có được xem là lịch sự ở đây không?", "Em hỏi thay vì tự suy đoán."], ["It may depend on the context and the person.", "Điều đó có thể tùy bối cảnh và từng người.", "Em tránh khái quát hóa tuyệt đối."], ["I hadn't realized that my assumption was inaccurate.", "Tôi đã không nhận ra giả định của mình chưa chính xác.", "Em thừa nhận hiểu lầm."], ["Thanks for explaining your perspective.", "Cảm ơn bạn đã giải thích góc nhìn của mình.", "Em kết thúc trao đổi với sự tôn trọng."]],
    practice: [{ prompt: "Chọn cách diễn đạt thận trọng nhất.", options: ["Everyone does this.", "People may do this in some contexts.", "This culture always does this."], correctIndex: 1, explanation: "May và some contexts tránh khái quát hóa." }, { prompt: "I didn't know ___ the gesture meant.", options: ["what", "that what", "what did"], correctIndex: 0, explanation: "Mệnh đề danh từ dùng what + chủ ngữ + động từ." }],
    visuals: ["🎎", "🌍", "💭", "🏷️", "🫂", "👋", "🙏", "🔭", "🔄", "🤝", "👋❓", "🧭", "💭⚠️", "🤝💬"],
  },
  {
    slug: "money-matters-advanced", title: "Bài 10 · Tài chính cá nhân", theme: "Money matters", description: "Phân tích lựa chọn tài chính, hỏi điều khoản và nêu quyết định có căn cứ.", grammar: "Câu điều kiện loại 3; danh động từ sau giới từ.",
    words: [["budget", "ngân sách"], ["interest", "lãi suất"], ["installment", "khoản trả góp"], ["afford", "có khả năng chi trả"], ["expense", "chi phí"], ["income", "thu nhập"], ["savings", "tiền tiết kiệm"], ["debt", "nợ"], ["fee", "phí"], ["terms", "điều khoản"]],
    sentences: [["Could you walk me through the fees and repayment terms?", "Anh/chị có thể giải thích từng khoản phí và điều khoản trả nợ không?", "Em yêu cầu thông tin rõ trước khi quyết định."], ["The interest rate increases after the first year.", "Lãi suất tăng sau năm đầu tiên.", "Nhân viên nêu một điều khoản quan trọng."], ["If I'd compared the offers, I might have saved more.", "Nếu đã so sánh các đề nghị, có lẽ tôi đã tiết kiệm hơn.", "Em nhìn lại một quyết định trong quá khứ."], ["I'll avoid borrowing until my budget is more stable.", "Tôi sẽ tránh vay cho đến khi ngân sách ổn định hơn.", "Em nêu quyết định dựa trên khả năng chi trả."]],
    practice: [{ prompt: "If I had checked the fees, I ___ differently.", options: ["would decide", "would have decided", "will decide"], correctIndex: 1, explanation: "Điều kiện loại 3: would have + quá khứ phân từ." }, { prompt: "I'm interested in ___ the options.", options: ["compare", "comparing", "to compare"], correctIndex: 1, explanation: "Sau giới từ in dùng danh động từ." }],
    visuals: ["📊", "📈", "🗓️", "💳", "🧾", "💵", "🐷", "📉", "🏷️", "📄", "🧾❓", "📈⏩", "⚖️💭", "🚫💳"],
  },
  {
    slug: "healthcare-communication", title: "Bài 11 · Giao tiếp y tế", theme: "Health care", description: "Mô tả triệu chứng có hệ thống, hỏi lại hướng dẫn và trao đổi với nhân viên y tế.", grammar: "Hiện tại hoàn thành tiếp diễn; câu tường thuật chỉ dẫn.",
    words: [["persistent", "kéo dài dai dẳng"], ["diagnosis", "chẩn đoán"], ["treatment", "điều trị"], ["prescription", "đơn thuốc"], ["side effect", "tác dụng phụ"], ["recover", "hồi phục"], ["consultation", "buổi tư vấn"], ["medical history", "tiền sử bệnh"], ["monitor", "theo dõi"], ["specialist", "bác sĩ chuyên khoa"]],
    sentences: [["I've been experiencing this pain for nearly a week.", "Tôi bị cơn đau này gần một tuần nay.", "Em mô tả triệu chứng và thời gian kéo dài."], ["Has it become more severe or more frequent?", "Nó có nặng hơn hoặc xảy ra thường xuyên hơn không?", "Nhân viên y tế hỏi mức độ thay đổi."], ["Could you explain how I should monitor the symptoms?", "Bác sĩ có thể giải thích tôi nên theo dõi triệu chứng thế nào không?", "Em hỏi lại hướng dẫn để tránh hiểu sai."], ["The doctor advised me to arrange a follow-up appointment.", "Bác sĩ khuyên tôi đặt lịch tái khám.", "Em thuật lại lời khuyên chuyên môn."]],
    practice: [{ prompt: "I ___ this pain for three days.", options: ["have been having", "am having", "had"], correctIndex: 0, explanation: "Hiện tại hoàn thành tiếp diễn nhấn mạnh tình trạng kéo dài đến hiện tại." }, { prompt: "The doctor advised me ___ the symptoms.", options: ["monitor", "to monitor", "monitoring"], correctIndex: 1, explanation: "Advise someone to do something." }],
    visuals: ["⏳", "🩺", "💊", "📄", "⚠️", "🌱", "👨‍⚕️", "📚", "📈", "🏥", "🤕⏳", "📊❓", "🩺💬", "📅✅"],
  },
  {
    slug: "social-issues", title: "Bài 12 · Các vấn đề xã hội", theme: "Social issues", description: "Thảo luận vấn đề xã hội dựa trên dữ liệu, thừa nhận nhiều góc nhìn và đề xuất giải pháp.", grammar: "Cấu trúc lập luận whereas/while; bị động tường thuật.",
    words: [["inequality", "bất bình đẳng"], ["access", "khả năng tiếp cận"], ["awareness", "nhận thức"], ["policy", "chính sách"], ["community", "cộng đồng"], ["evidence", "bằng chứng"], ["barrier", "rào cản"], ["initiative", "sáng kiến"], ["long-term", "dài hạn"], ["stakeholder", "bên liên quan"]],
    sentences: [["What evidence suggests this is a significant problem?", "Bằng chứng nào cho thấy đây là vấn đề đáng kể?", "Em yêu cầu cơ sở trước khi kết luận."], ["The report indicates that access remains unequal.", "Báo cáo cho thấy khả năng tiếp cận vẫn chưa đồng đều.", "Em viện dẫn nguồn thông tin."], ["While short-term support helps, long-term policy is also needed.", "Hỗ trợ ngắn hạn có ích, nhưng chính sách dài hạn cũng cần thiết.", "Em cân bằng hai hướng giải quyết."], ["Local communities should be involved in designing the initiative.", "Cộng đồng địa phương nên được tham gia thiết kế sáng kiến.", "Em đề xuất giải pháp có sự tham gia."]],
    practice: [{ prompt: "Hoàn thành: The policy is believed ___ effective.", options: ["be", "to be", "being"], correctIndex: 1, explanation: "Bị động tường thuật dùng is believed to be." }, { prompt: "___ funding matters, community trust is also essential.", options: ["While", "Because of", "Unless"], correctIndex: 0, explanation: "While dùng để cân bằng hai ý đúng cùng lúc." }],
    visuals: ["⚖️", "🚪", "📣", "📜", "🏘️", "🧾", "🚧", "💡", "🗓️", "👥", "🧾❓", "📊⚖️", "⏱️📜", "🏘️🤝"],
  },
  {
    slug: "advanced-review-three", title: "Ôn tập 3 · Bài 9–12", theme: "Văn hóa, tài chính, y tế và xã hội", description: "Củng cố diễn đạt thận trọng, phân tích quyết định, thuật lại lời khuyên và lập luận dựa trên bằng chứng.", grammar: "Tổng hợp cấu trúc của bài 9 đến bài 12.",
    words: [["analyze", "phân tích"], ["justify", "lý giải"], ["implication", "hàm ý, hệ quả"], ["nuanced", "có nhiều sắc thái"], ["credible", "đáng tin"], ["alternative", "phương án khác"], ["outcome", "kết quả"], ["consensus", "đồng thuận"], ["priority", "ưu tiên"], ["sustainable", "bền vững"]],
    sentences: [["The evidence appears credible, although the sample is limited.", "Bằng chứng có vẻ đáng tin dù mẫu nghiên cứu còn hạn chế.", "Em đánh giá nguồn một cách có sắc thái."], ["If we had considered other perspectives, we might have reached consensus.", "Nếu đã cân nhắc góc nhìn khác, có lẽ chúng ta đã đạt đồng thuận.", "Em nhìn lại quá trình ra quyết định."], ["The specialist advised us to monitor the long-term outcome.", "Chuyên gia khuyên chúng tôi theo dõi kết quả dài hạn.", "Em thuật lại khuyến nghị."], ["A sustainable solution requires both policy and community support.", "Giải pháp bền vững cần cả chính sách và hỗ trợ cộng đồng.", "Em kết luận bằng cách kết nối nhiều yếu tố."]],
    practice: [{ prompt: "If they had listened, they ___ an agreement.", options: ["might reach", "might have reached", "will reach"], correctIndex: 1, explanation: "Điều kiện loại 3 dùng might have + quá khứ phân từ." }, { prompt: "The expert advised us ___ more evidence.", options: ["collect", "to collect", "collecting"], correctIndex: 1, explanation: "Advise someone to do something." }],
    visuals: ["🔬", "🧾", "🔮", "🎨", "✅", "🔄", "🏁", "🤝", "🎯", "🌿", "🧾⚖️", "🔭🤝", "🩺📈", "🌿🏘️"],
  },
];

export function advancedEnglishBoardUrl(slug: string) {
  return `/advanced-english/boards/${slug}.svg`;
}

export function buildAdvancedEnglishLessons(unit: BasicEnglishUnitSeed) {
  return buildBasicEnglishLessons(unit, { boardUrl: advancedEnglishBoardUrl(unit.slug) });
}
