export const pronunciationLessons = [
  { id: "i", title: "/ɪ/ và /iː/", tip: "/ɪ/: thả lỏng môi, lưỡi cao vừa phải. /iː/: nâng lưỡi cao hơn, môi hơi kéo sang hai bên. Nghe chất âm, không chỉ độ dài.", mistake: "Tránh đọc ship và sheep thành cùng một âm.", words: ["ship", "sheep", "sit", "seat"], sentence: "The sheep is near the ship.", pair: ["ship", "sheep"] },
  { id: "ae", title: "/e/ và /æ/", tip: "Với /æ/, hạ hàm và mở miệng rộng hơn /e/, lưỡi ở phía trước. Đọc chậm bed rồi bad để cảm nhận hàm hạ xuống.", mistake: "Không thay cả hai bằng âm e tiếng Việt.", words: ["bed", "bad", "pen", "pan"], sentence: "The pen is next to the pan.", pair: ["bed", "bad"] },
  { id: "u", title: "/ʊ/ và /uː/", tip: "/ʊ/ ngắn và thả lỏng hơn. /uː/ có môi tròn và lưỡi cao hơn; vị trí có thể thay đổi theo giọng người nói.", mistake: "Nghe sự khác nhau của full và fool, không chỉ kéo dài cùng một âm.", words: ["full", "fool", "pull", "pool"], sentence: "The pool is full.", pair: ["full", "fool"] },
  { id: "th", title: "/θ/ và /ð/: âm th", tip: "Đặt nhẹ đầu lưỡi giữa hai hàm răng, thổi hơi qua khe. /θ/ không rung cổ; /ð/ có rung cổ. Chạm nhẹ tay lên cổ để tự kiểm tra.", mistake: "Đừng chặn luồng hơi hoàn toàn như t hoặc đ.", words: ["think", "thin", "this", "that"], sentence: "I think this is good.", pair: ["thin", "tin"] },
  { id: "fv", title: "/f/ và /v/", tip: "Răng trên chạm nhẹ môi dưới, hơi đi qua liên tục. /f/ không rung cổ; /v/ có rung cổ.", mistake: "Tránh khép cả hai môi như khi đọc b.", words: ["fan", "van", "fine", "vine"], sentence: "The van is very fast.", pair: ["fan", "van"] },
  { id: "sz", title: "/s/ và /z/", tip: "Đưa lưỡi gần vùng sau răng trên nhưng không chạm kín. Cho hơi đi qua; thêm rung cổ để chuyển từ /s/ sang /z/.", mistake: "Đừng bỏ âm cuối trong bus hoặc buzz.", words: ["sip", "zip", "bus", "buzz"], sentence: "The bees buzz near the bus.", pair: ["sip", "zip"] },
  { id: "sh", title: "/s/ và /ʃ/", tip: "/s/: môi ít tròn, luồng hơi hẹp. /ʃ/: môi hơi tròn, lưỡi lùi hơn. Nghe see rồi she để so sánh.", mistake: "Không dùng cùng một âm s cho see và she.", words: ["see", "she", "sip", "ship"], sentence: "She can see the ship.", pair: ["see", "she"] },
  { id: "lr", title: "/l/ và /r/", tip: "/l/: đầu lưỡi chạm vùng ngay sau răng trên. Với /r/ tiếng Anh Mỹ, lưỡi không chạm vòm miệng; môi có thể hơi tròn.", mistake: "Tránh rung đầu lưỡi nhiều lần khi đọc r theo giọng Mỹ.", words: ["light", "right", "long", "wrong"], sentence: "Turn right at the light.", pair: ["light", "right"] },
  { id: "end", title: "Giữ phụ âm cuối", tip: "Đọc từ chậm và hoàn tất động tác của âm cuối. Với /t/, đầu lưỡi chạm vùng sau răng trên; không cần bật hơi mạnh ở mọi vị trí.", mistake: "Đừng thêm âm ơ sau cat hoặc bỏ hẳn âm cuối.", words: ["cat", "cap", "back", "bag"], sentence: "Put the bag on the back seat.", pair: ["back", "bag"] },
  { id: "schwa", title: "/ə/: âm nhẹ", tip: "Thả lỏng miệng và lưỡi, đọc âm rất nhẹ ở âm tiết không nhấn: âm đầu của about. Không đọc mọi âm tiết mạnh ngang nhau.", mistake: "Không cố đọc rõ từng chữ cái trong âm tiết yếu.", words: ["about", "ago", "banana", "sofa"], sentence: "A banana is on the sofa.", pair: [] },
  { id: "stress", title: "Trọng âm từ", tip: "Nghe TEAcher, baNAna, aBOUT. Âm tiết được nhấn nổi bật hơn; các âm tiết khác nhẹ hơn. Dấu ˈ trong phiên âm đứng trước âm tiết nhấn.", mistake: "Không dùng một quy tắc vị trí trọng âm cho mọi từ.", words: ["teacher", "banana", "about", "beautiful"], sentence: "The teacher has a beautiful banana.", pair: [] },
  { id: "rhythm", title: "Nhịp câu và nối âm", tip: "Đọc theo cụm: pick it up. Chuyển liên tục từ phụ âm cuối sang nguyên âm đầu của từ kế tiếp. Nhấn những từ mang thông tin chính.", mistake: "Tránh ngắt lâu sau từng từ; trước hết hãy nói rõ rồi mới tăng tốc.", words: ["pick it up", "turn it on", "an apple", "a cup of tea"], sentence: "Please pick it up and put it on the table.", pair: [] },
];
