import { Role } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const unitSchema = z.object({ courseId: z.string().cuid(), title: z.string().trim().min(1).max(120), slug: z.string().regex(/^[a-z0-9-]+$/), theme: z.string().trim().min(1).max(100), description: z.string().trim().min(1).max(500), imageUrl: z.string().url().nullable().optional(), order: z.number().int().min(1) });
export async function POST(request: Request) { const user = await requireRole([Role.EDITOR, Role.ADMIN]); const parsed = unitSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "INVALID_INPUT" }, { status: 400 }); const unit = await prisma.unit.create({ data: { ...parsed.data, status: "DRAFT" } }); await prisma.auditLog.create({ data: { actorId: user.id, action: "CREATED", entityType: "Unit", entityId: unit.id } }); return NextResponse.json({ unit }, { status: 201 }); }
export async function PUT(request: Request) { const user = await requireRole([Role.EDITOR, Role.ADMIN]); const parsed = unitSchema.extend({ id: z.string().cuid() }).safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "INVALID_INPUT" }, { status: 400 }); const { id, courseId: _courseId, ...data } = parsed.data; void _courseId; const unit = await prisma.unit.update({ where: { id }, data: { ...data, status: "DRAFT" } }); await prisma.auditLog.create({ data: { actorId: user.id, action: "UPDATED", entityType: "Unit", entityId: unit.id } }); return NextResponse.json({ unit }); }
export async function DELETE(request: Request) { const user = await requireRole([Role.ADMIN]); const parsed = z.object({ id: z.string().cuid() }).safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "INVALID_INPUT" }, { status: 400 }); await prisma.unit.delete({ where: { id: parsed.data.id } }); await prisma.auditLog.create({ data: { actorId: user.id, action: "DELETED", entityType: "Unit", entityId: parsed.data.id } }); return NextResponse.json({ ok: true }); }
