"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Activity = { id: string; title: string; type: string; status: string };
type Lesson = { id: string; title: string; status: string; activities: Activity[] };
type Unit = { id: string; title: string; status: string; lessons: Lesson[] };
type Course = { id: string; title: string; status: string; units: Unit[] };
type Grade = { id: string; name: string; courses: Course[] };
export default function AdminWorkflow({ grades, role }: { grades: Grade[]; role: string }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function transition(entityType: string, entityId: string, status: string) { setMessage("Đang lưu…"); const response = await fetch("/api/admin/workflow", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entityType, entityId, status }) }); setMessage(response.ok ? "Đã cập nhật." : "Không thể cập nhật."); router.refresh(); }
  async function duplicate(unitId: string) { setMessage("Đang nhân bản…"); const response = await fetch("/api/admin/workflow", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ unitId }) }); setMessage(response.ok ? "Đã nhân bản unit thành bản nháp." : "Không thể nhân bản."); router.refresh(); }
  const controls = (type: string, id: string, status: string) => <div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">{status}</span>{status === "DRAFT" && <button onClick={() => transition(type, id, "IN_REVIEW")} className="text-xs font-black text-amber-700">Gửi duyệt</button>}{status === "IN_REVIEW" && role === "ADMIN" && <button onClick={() => transition(type, id, "PUBLISHED")} className="text-xs font-black text-emerald-700">Xuất bản</button>}{status !== "DRAFT" && <button onClick={() => transition(type, id, "DRAFT")} className="text-xs font-black text-slate-600">Về bản nháp</button>}</div>;
  return <section className="mt-7"><div className="mb-4 min-h-6 text-sm font-bold text-emerald-700">{message}</div><div className="space-y-5">{grades.map((grade) => grade.courses.length > 0 && <article key={grade.id} className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-2xl font-black">{grade.name}</h2>{grade.courses.map((course) => <div key={course.id} className="mt-4 rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-black">{course.title}</h3>{controls("Course", course.id, course.status)}</div><div className="mt-4 grid gap-3 lg:grid-cols-2">{course.units.map((unit) => <div key={unit.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{unit.title}</strong>{controls("Unit", unit.id, unit.status)}</div><button onClick={() => duplicate(unit.id)} className="mt-2 text-xs font-black text-sky-700">Nhân bản unit</button><div className="mt-3 space-y-2">{unit.lessons.map((lesson) => <details key={lesson.id} className="rounded-xl bg-white p-3"><summary className="cursor-pointer font-bold">{lesson.title} · {lesson.status}</summary><div className="mt-2">{controls("Lesson", lesson.id, lesson.status)}</div><div className="mt-3 space-y-2">{lesson.activities.map((activity) => <div key={activity.id} className="flex flex-wrap items-center justify-between gap-2 border-t pt-2 text-sm"><span>{activity.title} <small className="text-slate-500">{activity.type}</small></span>{controls("Activity", activity.id, activity.status)}</div>)}</div></details>)}</div></div>)}</div></div>)}</article>)}</div></section>;
}
