"use client";
import { useMemo, useState } from "react";

type Activity = { id: string; type: string; title: string; instruction: string; payload: Record<string, unknown>; order: number };
type Lesson = { id: string; title: string; description: string; estimatedMinutes: number; activities: Activity[] };
type SpeechWindow = Window & { SpeechRecognition?: new () => SpeechRecognition; webkitSpeechRecognition?: new () => SpeechRecognition };
type SpeechRecognition = { lang: string; interimResults: boolean; onresult: (event: { results: ArrayLike<{ 0: { transcript: string } }> }) => void; onerror: () => void; start: () => void };

function speak(text: string) { if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = "en-US"; utterance.rate = .85; window.speechSynthesis.speak(utterance); }

export default function LessonPlayer({ lessons }: { lessons: Lesson[] }) {
  const activities = useMemo(() => lessons.flatMap((lesson) => lesson.activities.map((activity) => ({ ...activity, lessonTitle: lesson.title }))), [lessons]);
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<Record<string, unknown>>({}); const [result, setResult] = useState<{ score: number; passed: boolean } | null>(null); const [pending, setPending] = useState(false);
  const activity = activities[index]; if (!activity) return <p className="mt-6 rounded-2xl bg-white p-5">Unit này chưa có hoạt động.</p>;
  const payload = activity.payload; const options = (payload.options || []) as Array<{ id: string; text: string }>; const pairs = (payload.pairs || []) as Array<{ left: string; right: string }>;
  async function submit() { setPending(true); const response = await fetch("/api/attempts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ activityId: activity.id, answer, durationSeconds: 0 }) }); const data = await response.json(); setPending(false); if (response.ok) setResult({ score: data.score, passed: data.passed }); }
  function next() { setIndex((value) => Math.min(value + 1, activities.length - 1)); setAnswer({}); setResult(null); }
  function startSpeech() { const speechWindow = window as SpeechWindow; const Recognition = speechWindow.SpeechRecognition || speechWindow.webkitSpeechRecognition; if (!Recognition) { setAnswer({ unsupported: true, confirmed: true }); return; } const recognition = new Recognition(); recognition.lang = "en-US"; recognition.interimResults = false; recognition.onresult = (event) => setAnswer({ transcript: event.results[0][0].transcript }); recognition.onerror = () => setAnswer({ unsupported: true, confirmed: true }); recognition.start(); }
  const inputClass = "mt-4 w-full rounded-2xl border border-slate-300 px-4 py-3";
  return <section className="mt-7 grid gap-5 lg:grid-cols-[250px_1fr]"><aside className="rounded-3xl bg-white p-4 shadow-sm"><p className="px-2 text-xs font-black uppercase tracking-wider text-emerald-700">Tiến độ unit</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><span className="block h-full bg-emerald-600" style={{ width: `${((index + (result?.passed ? 1 : 0)) / activities.length) * 100}%` }}/></div><div className="mt-5 space-y-2">{lessons.map((lesson) => <div key={lesson.id} className="rounded-xl bg-slate-50 p-3"><p className="text-sm font-black">{lesson.title}</p><p className="mt-1 text-xs text-slate-500">{lesson.activities.length} hoạt động · {lesson.estimatedMinutes} phút</p></div>)}</div></aside>
    <article className="rounded-3xl bg-white p-6 shadow-sm sm:p-9"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">{activity.lessonTitle} · {index + 1}/{activities.length}</p><h2 className="mt-3 text-3xl font-black">{activity.title}</h2><p className="mt-2 text-slate-600">{activity.instruction}</p>
      {(activity.type === "LISTEN_CHOOSE" || activity.type === "LISTEN_TYPE" || activity.type === "SPEAK_REPEAT") && <button onClick={() => speak(String(payload.text || payload.target || ""))} className="mt-5 rounded-2xl bg-sky-100 px-5 py-3 font-black text-sky-800">🔊 Nghe câu mẫu</button>}
      {activity.type === "FLASHCARD" && <div className="mt-5 rounded-3xl bg-amber-50 p-8 text-center"><p className="text-4xl font-black">{String(payload.front)}</p><p className="mt-3 text-xl text-amber-900">{String(payload.back)}</p><button onClick={() => setAnswer({ known: true })} className="mt-6 rounded-xl bg-emerald-700 px-5 py-3 font-black text-white">Em đã nhớ</button></div>}
      {(activity.type === "MULTIPLE_CHOICE" || activity.type === "LISTEN_CHOOSE") && <div className="mt-5 grid gap-3">{options.map((option) => <button onClick={() => setAnswer({ optionId: option.id })} key={option.id} className={`rounded-2xl border p-4 text-left font-bold ${answer.optionId === option.id ? "border-emerald-600 bg-emerald-50" : "border-slate-200"}`}>{option.text}</button>)}</div>}
      {activity.type === "MATCHING" && <div className="mt-5 space-y-3">{pairs.map((pair) => <label key={pair.left} className="grid items-center gap-3 rounded-2xl bg-slate-50 p-3 sm:grid-cols-2"><strong>{pair.left}</strong><select className="rounded-xl border bg-white p-2" onChange={(event) => { const current = (answer.pairs || []) as Array<{ left: string; right: string }>; setAnswer({ pairs: [...current.filter((item) => item.left !== pair.left), { left: pair.left, right: event.target.value }] }); }}><option value="">Chọn nghĩa</option>{pairs.map((item) => <option key={item.right}>{item.right}</option>)}</select></label>)}</div>}
      {(activity.type === "LISTEN_TYPE" || activity.type === "SENTENCE") && <input className={inputClass} placeholder="Nhập câu tiếng Anh" value={String(answer.text || "")} onChange={(event) => setAnswer({ text: event.target.value })}/>} 
      {activity.type === "SPEAK_REPEAT" && <div className="mt-5"><p className="rounded-2xl bg-slate-50 p-4 text-2xl font-black">{String(payload.target)}</p><button onClick={startSpeech} className="mt-3 rounded-xl bg-purple-100 px-5 py-3 font-black text-purple-800">🎙 Bắt đầu nói</button><p className="mt-3 text-sm text-slate-600">{answer.transcript ? `Em đã nói: ${answer.transcript}` : answer.unsupported ? "Trình duyệt không hỗ trợ nhận dạng giọng nói. Em có thể nghe và tự xác nhận đã nói theo." : "Bản ghi âm không được lưu."}</p></div>}
      {activity.type === "SHORT_WRITING" && <textarea className={`${inputClass} min-h-36`} placeholder={String(payload.prompt || "Viết câu trả lời của em")} value={String(answer.text || "")} onChange={(event) => setAnswer({ text: event.target.value })}/>} 
      {result ? <div className={`mt-6 rounded-2xl p-4 ${result.passed ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-900"}`}><p className="font-black">{result.passed ? `Tuyệt vời! ${result.score} điểm` : `Em đạt ${result.score} điểm. Hãy thử lại nhé.`}</p>{result.passed && index < activities.length - 1 && <button onClick={next} className="mt-3 rounded-xl bg-emerald-700 px-4 py-2 font-black text-white">Hoạt động tiếp theo →</button>}{result.passed && index === activities.length - 1 && <a href="/dashboard" className="mt-3 inline-block rounded-xl bg-emerald-700 px-4 py-2 font-black text-white">Hoàn thành unit</a>}{!result.passed && <button onClick={() => setResult(null)} className="mt-3 font-black underline">Làm lại</button>}</div> : <button disabled={pending || Object.keys(answer).length === 0} onClick={submit} className="mt-6 rounded-xl bg-emerald-700 px-6 py-3 font-black text-white disabled:opacity-40">{pending ? "Đang chấm…" : "Kiểm tra"}</button>}
    </article></section>;
}
